# docker-compose just to run our postgresql
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hospital_yuska
    ports:
      - "5432:5432"
    volumes:
      - ./db/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/02_seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
